---
# GLOBAL CONFIGURATION
# =============================================================================
# Define base workflow
# https://docs.gitlab.com/ee/ci/yaml/README.html#workflow
workflow:
  rules:
    # Do not run CI when commit title have following chars anywhere
    # WIP, NO-CI or 🚧 (gitmoji for "work in progress", aka :construction:)
    - if: $CI_COMMIT_MESSAGE =~ /(wip|WIP|NO-CI|🚧|:construction:)/
      when: never
    - if: $CI_MERGE_REQUEST_TITLE =~ /^(D|d)raft:/
      when: never
      # Allow pipelines from MR request to default branch
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      # Allow pipelines from specific source source on main branch
      # yamllint disable-line rule:line-length
    - if: $CI_PIPELINE_SOURCE =~ /(parent_pipeline|pipeline|push|web|webide|schedule)/ && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never

variables:
  # Set CI Feature Flag
  FF_SCRIPT_SECTIONS: true

stages:
  - pre-ci
  - lint
  - build
  - test
  - release
  - deploy
  - post-ci

# Fake jobs that simply exit 0 to enable CI
Dumb Job - Exit 0:
  image: alpine:latest
  stage: pre-ci
  script:
    - exit 0
  rules:
    - when: always

include:
  - .gitlab/*.yml
  - .gitlab/*.yaml
  - .gitlab/*/*.yml
  - .gitlab/*/*.yaml
