---
defaults:
  copyright:
    mail: code@romaindeville.fr
    name: Romain Deville
  licenses:
    date:
      firstYear: 2025
    primary: MIT
    secondaries:
      - BEERWARE
  project:
    baseURL: https://framagit.org/rdeville-public
    name: Project
    slug: project
