---
project:
  type: yaml
  multiline: true
  help: |
    Struct describing project information respecting schema in
    'jsonschema/project.json'.
    For instance:
    ```
    name: My Awesome Project
    baseURL: https://git.domain.tld/username
    slug: my-awesome-project
    desc: |
      My awesome project description
    ```
  validator: "{{ project | jsonschema('schemas/project.json') }}"

licenses:
  type: yaml
  multiline: true
  help: |
    A set of key values respecting schema in 'jsonschema/licenses.json'.
    For instance:
    ```
    date:
      firstYear: 2025
      lastYear: 2100
    primary: MIT
    secondaries:
      - BEERWARE
    ```
  validator: "{{ licenses | jsonschema('schemas/licenses.json') }}"

copyright:
  type: yaml
  multiline: true
  help: |
    A set of key values respecting schema in 'jsonschema/copyright.json' to
    specify copyright hold information.
    For instance:
    ```
    name: Jon Doe
    mail: jon.doe@domain.tld
    ```
  validator: "{{ copyright | jsonschema('schemas/copyright.json') }}"

maintainers:
  type: yaml
  multiline: true
  help: |
    A set of key values respecting schema in 'jsonschema/maintainers.json' to
    specify maintainers of the repository.
    For instance:
    ```
    - name: Jon Doe
      mail: jon.doe@domain.tld
    - name: Jane Doe
      mail: jane.doe@anotherdomain.tld
    ```
  validator: "{{ maintainers | jsonschema('schemas/maintainers.json') }}"

abuse_mail_code_of_conduct:
  type: str
  help: |
    The mail address to contact in case of abuse according to the CODE OF CONDUCT

security:
  type: yaml
  multiline: true
  help: |-
    Information about the security team. Will be used at lease in CONTRIBUTING.
    Should be respecting schema in 'jsonschema/security.json'.
    For instance:
    ```
    mail: security@domain.tld
    GPGPublic: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      ...
      -----END PGP PUBLIC KEY BLOCK-----
    ```
