#!/usr/bin/env bash

# shellcheck disable=SC2034
SCRIPTPATH="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit 1
  pwd -P
)"
SCRIPTNAME="$(basename "$0")"
set -e

init_logger() {
  local log_file="${XDG_CACHE_HOME:-${HOME}/.cache}/snippets/_log.sh"
  local last_download_file="/tmp/_log.time"
  local delai=14400 # 4 hours
  # shellcheck disable=SC2155
  local curr_time=$(date +%s)
  local time="$((curr_time - $(cat "${last_download_file}" 2>/dev/null || echo "0")))"

  if ! [[ -f "${log_file}" ]] ||
    { [[ -f "${log_file}" ]] && [[ "${time}" -gt "${delai}" ]]; }; then
    if ping -q -c 1 framagit.org &>/dev/null; then
      # shellcheck disable=SC1090
      source <(curl -s https://framagit.org/-/snippets/7183/raw/main/_get_log.sh)
      echo "${curr_time}" >"${last_download_file}"
    else
      echo -e "\033[1;33m[WARNING]\033[0;33m Unable to get last logger version, will use \`echo\`.\033[0m"
      _log() {
        echo "$@"
      }
    fi
  else
    # shellcheck disable=SC1090
    source <(cat "${log_file}")
  fi
}

_copier_init() {
  local pythonVenv=/tmp/venv/copier
  python3 -m venv "${pythonVenv}"
  # shellcheck disable=SC1091
  source "${pythonVenv}/bin/activate"
  pip install uv
  uv run \
    --with jinja2-time \
    --with copier-template-extensions \
    --with jinja2-jsonschema \
    --with requests \
    copier \
    copy \
    --trust \
    -a \
    "${copier_cfg//"${PWD}/"/}" \
    git+https://framagit.org/rdeville-public/programs/copier-generic-template \
    "${PWD}"
  deactivate
}

_git_init() {
  if ! [[ -d "${PWD}/.git" ]]; then
    git init
  fi

  local msg="🎉 Initial Empty Commit"
  if ! git log | grep -q "${msg}"; then
    git commit --allow-empty -m "${msg}"
  fi

  local tag="v0.0.0"
  local tag_msg="🔖 Initial Empty Release"
  if ! git tag | grep -q "${tag}"; then
    git tag "${tag}" -m "${tag_msg}"
  fi

  local branch="feat/copier-init"
  if ! git branch | grep -q "${branch}"; then
    git checkout -b "${branch}"
  fi
}

main() {
  export DEBUG_LEVEL="${DEBUG_LEVEL:-INFO}"
  init_logger

  local copier_cfg="${PWD}/.copier.yaml"
  local opts tmp

  _log "WARNING" "THIS SCRIPT CALL ANOTHER SCRIPT USING CURL !"
  _log "WARNING" "Have you read the content of these scripts and want to continue ?"
  _log "WARNING" "Type 'yes' or 'Yes' to continue"
  read -r answer </dev/tty
  if ! [[ "${answer}" =~ (Yes|yes) ]]; then
    _log "INFO" "Stopping the script execution."
  fi

  _git_init
  _copier_init

  curl https://framagit.org/rdeville-public/programs/copier-generic-template/-/raw/main/scripts/copierCommit |
    bash -s -- copy

  return
}

main
